publishDir = "docs"
baseUrl = "/blog/"
languageCode = "en-us"
title = "Collection of Articles on ML"
theme = "hugo-book"
[params]
  BookTheme = "auto"
  dateFormat = "Mon, Jan 2, 2006"
  math = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

